### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by kerneljay** [Sharkiiie/lf-timecycle#1]
I can not get this to work

Steps to reproduce
-Download resource via ZIP
-Put into server 
-Restart and made sure it is ensured
-No command is registered and no menu comes up

**Comment by AkinoKitsu** [comment]
Try the command in F8 instead of chat.
Not sure why but it doesn't seem to work in chat

**Comment by AkinoKitsu** [comment]
Closed as stale.
(I'm cleaning up my GH, sorry if you get a ping :P)
